create sequence hib_seq start with 1 increment by 100;

    create table classe (
       id integer not null,
        code_naf varchar(255),
        coeff_calcul_indice double,
        coeff_redressement_niveau double,
        libelle_nomenclature varchar(255),
        groupe_id integer,
        primary key (id)
    );

    create table declaration (
       id integer not null,
        date timestamp,
        montant double,
        version bigint,
        entreprise_id integer,
        primary key (id)
    );

    create table declaration_aud (
       id integer not null,
        rev integer not null,
        revtype tinyint,
        date timestamp,
        montant double,
        montant_mod boolean,
        entreprise_id integer,
        primary key (id, rev)
    );

    create table division (
       id integer not null,
        code_naf varchar(255),
        coeff_calcul_indice double,
        coeff_redressement_niveau double,
        libelle_nomenclature varchar(255),
        section_id integer,
        primary key (id)
    );

    create table entreprise (
       id integer not null,
        rue varchar(255),
        numero varchar(255),
        pays varchar(255),
        type_voie varchar(255),
        ville varchar(255),
        coeff_calcul_indice double,
        coeff_redressement_entreprise double,
        date_creation date,
        denomination varchar(255),
        nom_fondateur varchar(50),
        prenom_fondateur varchar(50),
        siren varchar(9) not null,
        telephone varchar(20),
        url varchar(50),
        version bigint,
        sous_classe_id integer,
        primary key (id)
    );

    create table entreprise_aud (
       id integer not null,
        rev integer not null,
        revtype tinyint,
        rue varchar(255),
        numero varchar(255),
        pays varchar(255),
        type_voie varchar(255),
        ville varchar(255),
        adresse_mod boolean,
        coeff_calcul_indice double,
        coeff_calcul_indice_mod boolean,
        coeff_redressement_entreprise double,
        coeff_redressement_entreprise_mod boolean,
        date_creation date,
        date_creation_mod boolean,
        denomination varchar(255),
        denomination_mod boolean,
        nom_fondateur varchar(50),
        nom_fondateur_mod boolean,
        prenom_fondateur varchar(50),
        prenom_fondateur_mod boolean,
        siren varchar(9),
        siren_mod boolean,
        telephone varchar(20),
        telephone_mod boolean,
        url varchar(50),
        url_mod boolean,
        declarations_mod boolean,
        primary key (id, rev)
    );

    create table groupe (
       id integer not null,
        code_naf varchar(255),
        coeff_calcul_indice double,
        coeff_redressement_niveau double,
        libelle_nomenclature varchar(255),
        division_id integer,
        primary key (id)
    );

    create table indice_annuel (
       id integer not null,
        derniere_maj timestamp,
        valeur double,
        year timestamp,
        sous_classe_id integer,
        primary key (id)
    );

    create table indice_mensuel (
       id integer not null,
        derniere_maj timestamp,
        valeur double,
        month timestamp,
        sous_classe_id integer,
        primary key (id)
    );

    create table revinfo (
       rev integer generated by default as identity (start with 1),
        revtstmp bigint,
        primary key (rev)
    );

    create table section (
       id integer not null,
        code_naf varchar(255),
        coeff_calcul_indice double,
        coeff_redressement_niveau double,
        libelle_nomenclature varchar(255),
        primary key (id)
    );

    create table sous_classe (
       id integer not null,
        code_naf varchar(255),
        coeff_calcul_indice double,
        coeff_redressement_niveau double,
        libelle_nomenclature varchar(255),
        classe_id integer,
        primary key (id)
    );

    alter table classe 
       add constraint FKjuqmi2c71pj7j2obnko08tx0s 
       foreign key (groupe_id) 
       references groupe;

    alter table declaration 
       add constraint FKci8f3vilkcfbmw19i7x3pb6ue 
       foreign key (entreprise_id) 
       references entreprise;

    alter table declaration_aud 
       add constraint FKmbkbd2ihup5fct4dus6i6fc79 
       foreign key (rev) 
       references revinfo;

    alter table division 
       add constraint FKfxtl8rcoxwmuepofk5hh4y6bi 
       foreign key (section_id) 
       references section;

    alter table entreprise 
       add constraint FK6ooojiniylgfwcs9ko12og7vl 
       foreign key (sous_classe_id) 
       references sous_classe;

    alter table entreprise_aud 
       add constraint FKerm2kd0m3hf1jvdn3e55m3s5j 
       foreign key (rev) 
       references revinfo;

    alter table groupe 
       add constraint FK4a74lbudkjs9jmctp8xip8gv4 
       foreign key (division_id) 
       references division;

    alter table indice_annuel 
       add constraint FKswhj4nx7k4nso80dwr3bkcsy4 
       foreign key (sous_classe_id) 
       references sous_classe;

    alter table indice_mensuel 
       add constraint FKjjqrpechha6w64uo9kseq24fr 
       foreign key (sous_classe_id) 
       references sous_classe;

    alter table sous_classe 
       add constraint FKacinpkh4ogm30bvg8xfom17dg 
       foreign key (classe_id) 
       references classe;
